name: Docker build and push

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: hello-go
      MANIFEST_REPOSITORY: codequokka/github-actions-pull-manifest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: Exec hadolint
        uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: Dockerfile

      - name: Get current tag name of repo
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.tag }}

      - name: dispatch update-manifests
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          repository: ${{ env.MANIFEST_REPOSITORY }}
          token: ${{ secrets.REPO_ACCESS_PAT }}
          event-type: update-manifest
          client-payload: '{"tag": "${{ steps.vars.outputs.tag }}"}'
